#!/bin/sh
#
# Copyright 2016 Ben Walsh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# $Header$

set -eu

NAME=$1
shift
CMD=$1
shift

MYDIR=$(dirname $(readlink -f "$0"))

umask 0027

. $HOME/.cronrun

USER=$(id -un)

LOGUSER=$USER

DATE=$(date +%Y%m%d%H%M)

LOGDIR=/home/$LOGUSER/log

mkdir -p $LOGDIR

LOGFILE=${LOGDIR}/${NAME}.${DATE}
STATFILE=${LOGDIR}/${NAME}.status

TMPFILE=/tmp/cronrun.$$

PREVRC=''
[ -s $STATFILE ] && PREVRC=$(cat $STATFILE)

set >${LOGFILE}.env

RC=0
$CMD "$@" </dev/null >${TMPFILE}.log 2>&1 || RC=$?

echo $RC >$STATFILE

mv ${TMPFILE}.log ${LOGFILE}.log

if [ "$RC" != "$PREVRC" ]
then
    SUBJECT='FAILURE'
    [ $RC -eq 0 ] && SUBJECT='Success'
    SUBJECT="${SUBJECT}: $NAME"

    tail -50 ${LOGFILE}.log | $CRONRUN_MAILX -s "$SUBJECT" -r $CRONRUN_MAILEE $CRONRUN_MAILEE
fi
